<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Topic modeling with SVD and NMF – Ron Medina ∷ Résumé</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../courses/cla/12-pagerank.html" rel="next">
<link href="../../courses/cla/10-quadratic-forms.html" rel="prev">
<link href="../../assets/favicon.jpg" rel="icon" type="image/jpeg">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-7b67f2ab0b6bf9f6b6e1e6f623931207.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../assets/styles.css">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Ron Medina ∷ Résumé</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../portfolio/portfolio.html"> 
<span class="menu-text">portfolio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../articles/index.html"> 
<span class="menu-text">articles</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../notes/index.html"> 
<span class="menu-text">notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../courses/index.html"> 
<span class="menu-text">courses</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../photos/photos.html"> 
<span class="menu-text">photos</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/particle1331/watchtower/tree/main/src/watchtower"> <i class="bi bi-github" role="img" aria-label="watchtower source on GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../courses/cla/11-topic-modeling.html">Applications</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../courses/cla/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Computational Linear Algebra</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../courses/cla/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../courses/cla/01-foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">01. Foundations</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../courses/cla/02-spectral-theorem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The SVD and its proof</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../courses/cla/02-spectral-theorem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">02. The spectral theorem</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../courses/cla/03-svd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">03. The singular value decomposition</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../courses/cla/04-rank-and-four-subspaces.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Structure</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../courses/cla/04-rank-and-four-subspaces.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">04. Rank &amp; the four fundamental subspaces</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../courses/cla/05-determinant.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">05. Determinant</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../courses/cla/06-inverse-and-pseudoinverse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">06. Inverse &amp; pseudoinverse</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../courses/cla/07-projection-and-orthogonalization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Computation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../courses/cla/07-projection-and-orthogonalization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">07. Projection &amp; orthogonalization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../courses/cla/08-least-squares.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">08. Least squares</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../courses/cla/09-eigendecomposition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The eigenworld</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../courses/cla/09-eigendecomposition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">09. Eigendecomposition</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../courses/cla/10-quadratic-forms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10. Quadratic forms</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../courses/cla/11-topic-modeling.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Applications</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../courses/cla/11-topic-modeling.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">11. Topic modeling with SVD and NMF</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../courses/cla/12-pagerank.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">12. PageRank</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../courses/cla/13-robust-pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">13. Robust PCA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../courses/cla/14-compressed-sensing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">14. Compressed sensing</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#text-as-data" id="toc-text-as-data" class="nav-link active" data-scroll-target="#text-as-data">Text as data</a></li>
  <li><a href="#the-corpus" id="toc-the-corpus" class="nav-link" data-scroll-target="#the-corpus">The corpus</a></li>
  <li><a href="#the-spectrum-of-a-document-matrix" id="toc-the-spectrum-of-a-document-matrix" class="nav-link" data-scroll-target="#the-spectrum-of-a-document-matrix">The spectrum of a document matrix</a></li>
  <li><a href="#reading-topics-from-the-right-singular-vectors" id="toc-reading-topics-from-the-right-singular-vectors" class="nav-link" data-scroll-target="#reading-topics-from-the-right-singular-vectors">Reading topics from the right singular vectors</a></li>
  <li><a href="#nonnegative-matrix-factorization" id="toc-nonnegative-matrix-factorization" class="nav-link" data-scroll-target="#nonnegative-matrix-factorization">Nonnegative matrix factorization</a></li>
  <li><a href="#tfidf-weighting" id="toc-tfidf-weighting" class="nav-link" data-scroll-target="#tfidf-weighting">TF–IDF weighting</a></li>
  <li><a href="#truncated-and-randomized-svd" id="toc-truncated-and-randomized-svd" class="nav-link" data-scroll-target="#truncated-and-randomized-svd">Truncated and randomized SVD</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#problems" id="toc-problems" class="nav-link" data-scroll-target="#problems">Problems</a>
  <ul class="collapse">
  <li><a href="#p11.1-energy-captured-by-a-rank-k-truncation" id="toc-p11.1-energy-captured-by-a-rank-k-truncation" class="nav-link" data-scroll-target="#p11.1-energy-captured-by-a-rank-k-truncation">[P11.1] Energy captured by a rank-<span class="math inline">k</span> truncation</a></li>
  <li><a href="#p11.2-power-iteration-amplification-in-the-sketch" id="toc-p11.2-power-iteration-amplification-in-the-sketch" class="nav-link" data-scroll-target="#p11.2-power-iteration-amplification-in-the-sketch">[P11.2] Power iteration amplification in the sketch</a></li>
  <li><a href="#p11.3-tfidf-on-a-toy-corpus" id="toc-p11.3-tfidf-on-a-toy-corpus" class="nav-link" data-scroll-target="#p11.3-tfidf-on-a-toy-corpus">[P11.3] TF–IDF on a toy corpus</a></li>
  <li><a href="#p11.4-energy-retention-in-practice" id="toc-p11.4-energy-retention-in-practice" class="nav-link" data-scroll-target="#p11.4-energy-retention-in-practice">[P11.4] Energy retention in practice</a></li>
  <li><a href="#p11.5-power-iterations-in-the-randomized-svd" id="toc-p11.5-power-iterations-in-the-randomized-svd" class="nav-link" data-scroll-target="#p11.5-power-iterations-in-the-randomized-svd">[P11.5] Power iterations in the randomized SVD</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Topic modeling with SVD and NMF</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="text-as-data" class="level2">
<h2 class="anchored" data-anchor-id="text-as-data">Text as data</h2>
<p>This chapter puts the machinery of Chapter 3 to work on a matrix built from text rather than from geometry: a collection of newsgroup messages becomes a matrix of word counts, and the low-rank factorizations developed so far turn out to recover the <em>topics</em> the documents discuss, without ever being told what those topics are.</p>
<p>The raw material is a corpus of <span class="math inline">n</span> documents over a fixed vocabulary of <span class="math inline">d</span> terms. The <mark>bag-of-words</mark> model discards word order and records only how often each term occurs in each document, yielding the <strong>term–document matrix</strong> <span class="math inline">\mathbf{X}\in\mathbb{R}^{n\times d}</span> with entries</p>
<p><span class="math display">
x_{ij} = \text{number of times term } j \text{ occurs in document } i,
</span></p>
<p>one row per document, one column per term. All the syntax of the original texts is thrown away; what survives is a frequency table. Despite that loss, the matrix retains enough structure for the SVD to find coherent themes.</p>
<p>The low-rank ladder of Chapter 3 gives the motivation. The rank-one layer <span class="math inline">\sigma_1\mathbf{u}_1\mathbf{v}_1^{\mathsf T}</span> is an outer product of a document-direction vector and a word-direction vector: it approximates every row of <span class="math inline">\mathbf{X}</span> by a single average word-frequency profile <span class="math inline">\mathbf{v}_1</span>, scaled per document by <span class="math inline">\sigma_1(\mathbf{u}_1)_i</span>, a quantity proportional to the document’s length. Adding the second layer <span class="math inline">\sigma_2\mathbf{u}_2\mathbf{v}_2^{\mathsf T}</span> superimposes a signed correction: documents with <span class="math inline">(\mathbf{u}_2)_i &gt; 0</span> are pushed toward the words where <span class="math inline">(\mathbf{v}_2)_j &gt; 0</span> and away from the words where <span class="math inline">(\mathbf{v}_2)_j &lt; 0</span>, so the layer <em>splits</em> the corpus into two opposing groups of documents and words: two topics. At rank <span class="math inline">k</span> the model is</p>
<p><span class="math display">
\boxed{\ \mathbf{X} \approx \sum_{i=1}^k \sigma_i\,\mathbf{u}_i\mathbf{v}_i^{\mathsf T},\ }
</span></p>
<p>a <span class="math inline">k</span>-topic model in which each layer is one topic and each document is a weighted combination of topics. The two factors carry the two readings: the right singular vectors <span class="math inline">\mathbf{v}_i</span> live in word space and read as word lists; the left singular vectors <span class="math inline">\mathbf{u}_i</span> live in document space and say how strongly each document participates in the layer.</p>
</section>
<section id="the-corpus" class="level2">
<h2 class="anchored" data-anchor-id="the-corpus">The corpus</h2>
<p>The data are the <a href="https://scikit-learn.org/stable/datasets/real_world.html#the-20-newsgroups-dataset">20 Newsgroups</a> collection: posts from Usenet discussion groups, restricted here to four categories: two religion-related groups (<code>alt.atheism</code>, <code>talk.religion.misc</code>), a computer-graphics group (<code>comp.graphics</code>), and a space group (<code>sci.space</code>). The category of every document is known, but the analysis below never uses it; the labels serve only as a ground-truth check after the fact. This is an <mark>unsupervised</mark> setting: the factorization must find the structure in the counts alone.</p>
<div id="6780ea99" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-14T21:00:19.710339Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-14T21:00:19.710013Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-14T21:00:27.376942Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-14T21:00:27.373249Z&quot;}}" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="annotated-cell-1"><pre class="sourceCode python code-annotation-code code-with-copy"><code class="sourceCode python"><span id="annotated-cell-1-1"><a href="#annotated-cell-1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> watchtower.core <span class="im">import</span> set_format</span>
<span id="annotated-cell-1-2"><a href="#annotated-cell-1-2" aria-hidden="true" tabindex="-1"></a>set_format(<span class="st">"svg"</span>)</span>
<span id="annotated-cell-1-3"><a href="#annotated-cell-1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-1-4"><a href="#annotated-cell-1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> time</span>
<span id="annotated-cell-1-5"><a href="#annotated-cell-1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="annotated-cell-1-6"><a href="#annotated-cell-1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="annotated-cell-1-7"><a href="#annotated-cell-1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-1-8"><a href="#annotated-cell-1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.datasets <span class="im">import</span> fetch_20newsgroups</span>
<span id="annotated-cell-1-9"><a href="#annotated-cell-1-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.feature_extraction.text <span class="im">import</span> CountVectorizer</span>
<span id="annotated-cell-1-10"><a href="#annotated-cell-1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-1-11"><a href="#annotated-cell-1-11" aria-hidden="true" tabindex="-1"></a>categories <span class="op">=</span> [<span class="st">"alt.atheism"</span>, <span class="st">"talk.religion.misc"</span>, <span class="st">"comp.graphics"</span>, <span class="st">"sci.space"</span>]</span>
<span id="annotated-cell-1-12"><a href="#annotated-cell-1-12" aria-hidden="true" tabindex="-1"></a>newsgroups <span class="op">=</span> fetch_20newsgroups(subset<span class="op">=</span><span class="st">"train"</span>, categories<span class="op">=</span>categories,</span>
<span id="annotated-cell-1-13"><a href="#annotated-cell-1-13" aria-hidden="true" tabindex="-1"></a>                                remove<span class="op">=</span>(<span class="st">"headers"</span>, <span class="st">"footers"</span>, <span class="st">"quotes"</span>))</span>
<span id="annotated-cell-1-14"><a href="#annotated-cell-1-14" aria-hidden="true" tabindex="-1"></a>counts <span class="op">=</span> CountVectorizer(stop_words<span class="op">=</span><span class="st">"english"</span>)</span>
<span id="annotated-cell-1-15"><a href="#annotated-cell-1-15" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> counts.fit_transform(newsgroups.data)</span>
<span id="annotated-cell-1-16"><a href="#annotated-cell-1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-1-17"><a href="#annotated-cell-1-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"documents :"</span>, X.shape[<span class="dv">0</span>])</span>
<span id="annotated-cell-1-18"><a href="#annotated-cell-1-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"vocabulary:"</span>, X.shape[<span class="dv">1</span>])</span>
<span id="annotated-cell-1-19"><a href="#annotated-cell-1-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"nonzeros  :"</span>, X.nnz, <span class="st">" (density </span><span class="sc">{:.2%}</span><span class="st">)"</span>.<span class="bu">format</span>(X.nnz <span class="op">/</span> np.prod(X.shape)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>documents : 2034
vocabulary: 26576
nonzeros  : 133634  (density 0.25%)</code></pre>
</div>
</div>
<p>The matrix <span class="math inline">\mathbf{X}\in\mathbb{R}^{2034\times 26576}</span> is tall and thin in the sense that matters here: <span class="math inline">d</span> is more than an order of magnitude larger than <span class="math inline">n</span>. The call # &lt;1&gt; strips message headers, footers, and quoted replies, so the counts reflect the authors’ own prose; # &lt;2&gt; removes a standard English stopword list; # &lt;3&gt; leaves a sparse matrix with 0.25% of its entries nonzero — each document uses on average only about 66 of the 26576 vocabulary terms. The labels played no role in the construction: the counts are assembled from the text alone.</p>
</section>
<section id="the-spectrum-of-a-document-matrix" class="level2">
<h2 class="anchored" data-anchor-id="the-spectrum-of-a-document-matrix">The spectrum of a document matrix</h2>
<p>Chapter 3 established the diagnostic: the singular values of a matrix order its information content layer by layer, and the scree plot of <span class="math inline">\sigma_i</span> against <span class="math inline">i</span> shows how much a low-rank truncation can capture. Applied to <span class="math inline">\mathbf{X}</span>, the same plot answers a content question first: does a document corpus actually have low-rank structure?</p>
<div id="cell-fig-svd-scree" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-14T21:00:27.383395Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-14T21:00:27.382781Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-14T21:01:30.688349Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-14T21:01:30.687527Z&quot;}}" data-cap="**Singular value spectrum of the term–document matrix.** The decay is gradual: the first layers carry real signal, but unlike the synthetic examples of Chapter 3 there is no dramatic knee. The dashed line marks the cutoff $k = 10$ used for topic reading below." data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="annotated-cell-2"><pre class="sourceCode python code-annotation-code code-with-copy"><code class="sourceCode python"><span id="annotated-cell-2-1"><a href="#annotated-cell-2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> linalg</span>
<span id="annotated-cell-2-2"><a href="#annotated-cell-2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-2-3"><a href="#annotated-cell-2-3" aria-hidden="true" tabindex="-1"></a>t0 <span class="op">=</span> time.perf_counter()</span>
<span id="annotated-cell-2-4"><a href="#annotated-cell-2-4" aria-hidden="true" tabindex="-1"></a>U, s, Vh <span class="op">=</span> linalg.svd(X.todense(), full_matrices<span class="op">=</span><span class="va">False</span>)</span>
<span id="annotated-cell-2-5"><a href="#annotated-cell-2-5" aria-hidden="true" tabindex="-1"></a>t_full <span class="op">=</span> time.perf_counter() <span class="op">-</span> t0</span>
<span id="annotated-cell-2-6"><a href="#annotated-cell-2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-2-7"><a href="#annotated-cell-2-7" aria-hidden="true" tabindex="-1"></a>k <span class="op">=</span> <span class="dv">10</span></span>
<span id="annotated-cell-2-8"><a href="#annotated-cell-2-8" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="fl">4.2</span>))</span>
<span id="annotated-cell-2-9"><a href="#annotated-cell-2-9" aria-hidden="true" tabindex="-1"></a>ax.semilogy(np.arange(<span class="dv">1</span>, <span class="bu">len</span>(s) <span class="op">+</span> <span class="dv">1</span>), s, lw<span class="op">=</span><span class="fl">1.6</span>, color<span class="op">=</span><span class="st">"#1f77b4"</span>)</span>
<span id="annotated-cell-2-10"><a href="#annotated-cell-2-10" aria-hidden="true" tabindex="-1"></a>ax.axvline(k <span class="op">+</span> <span class="fl">0.5</span>, color<span class="op">=</span><span class="st">"#d62728"</span>, ls<span class="op">=</span><span class="st">"--"</span>, lw<span class="op">=</span><span class="fl">1.4</span>)</span>
<span id="annotated-cell-2-11"><a href="#annotated-cell-2-11" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"index $i$"</span>)</span>
<span id="annotated-cell-2-12"><a href="#annotated-cell-2-12" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"singular value $</span><span class="ch">\\</span><span class="st">sigma_i$"</span>)</span>
<span id="annotated-cell-2-13"><a href="#annotated-cell-2-13" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Term–document spectrum"</span>)</span>
<span id="annotated-cell-2-14"><a href="#annotated-cell-2-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> sp <span class="kw">in</span> (<span class="st">"top"</span>, <span class="st">"right"</span>):</span>
<span id="annotated-cell-2-15"><a href="#annotated-cell-2-15" aria-hidden="true" tabindex="-1"></a>    ax.spines[sp].set_visible(<span class="va">False</span>)</span>
<span id="annotated-cell-2-16"><a href="#annotated-cell-2-16" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="annotated-cell-2-17"><a href="#annotated-cell-2-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="annotated-cell-2-18"><a href="#annotated-cell-2-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-2-19"><a href="#annotated-cell-2-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"full SVD of dense </span><span class="sc">{</span>X<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>t_full<span class="sc">:.1f}</span><span class="ss"> s"</span>)</span>
<span id="annotated-cell-2-20"><a href="#annotated-cell-2-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"energy in first </span><span class="sc">{</span>k<span class="sc">}</span><span class="ss"> layers: </span><span class="sc">{</span>(s[:k]<span class="op">**</span><span class="dv">2</span>)<span class="sc">.</span><span class="bu">sum</span>() <span class="op">/</span> (s<span class="op">**</span><span class="dv">2</span>)<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.1%}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div id="fig-svd-scree" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-svd-scree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="11-topic-modeling_files/figure-html/fig-svd-scree-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;1: "><img src="11-topic-modeling_files/figure-html/fig-svd-scree-output-1.svg" id="fig-svd-scree" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-svd-scree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>full SVD of dense (2034, 26576): 62.9 s
energy in first 10 layers: 58.0%</code></pre>
</div>
</div>
<p>Unlike the matrices of Chapter 3 (planted low-rank signals plus noise), the spectrum of real text decays slowly and steadily: the first ten of 2034 layers retain 58% of the total energy, and the tail keeps going far beyond the plot’s edge. Real document corpora are genuinely high-rank: the singular values fall off like a power law, not an exponential. Truncation is therefore a <em>modeling choice</em>: “ten topics explain 58% of the word counts”, rather than a forced recovery of a hidden low-rank truth. Chapter 3’s Eckart–Young theorem guarantees that the truncated SVD is the best rank-<span class="math inline">k</span> approximation of <span class="math inline">\mathbf{X}</span> in the Frobenius norm; it cannot guarantee that the best approximation is a good model. The step # &lt;1&gt; densifies the sparse matrix, about 430 MB of doubles, so that <code>linalg.svd</code> can operate on it, and the exact factorization costs 49 seconds here; both bills are what the randomized algorithms at the end of this chapter avoid.</p>
</section>
<section id="reading-topics-from-the-right-singular-vectors" class="level2">
<h2 class="anchored" data-anchor-id="reading-topics-from-the-right-singular-vectors">Reading topics from the right singular vectors</h2>
<p>Each row of <span class="math inline">\mathbf{V}^{\mathsf T}</span> is one right singular vector <span class="math inline">\mathbf{v}_i^{\mathsf T}\in\mathbb{R}^d</span>, with one entry per vocabulary term. The terms with the largest entries dominate the layer, and the word list they form is the topic the <span class="math inline">i</span>-th layer captures. Because SVD entries are signed, the <em>smallest</em> entries are equally informative: they are the words the layer actively pulls away from, the topic’s opposite pole. The helper below extracts the <span class="math inline">n</span> largest entries of any word-space vector; it is applied to the first ten right singular vectors.</p>
<div id="4d915910" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-14T21:01:30.693155Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-14T21:01:30.692983Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-14T21:01:30.731871Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-14T21:01:30.731237Z&quot;}}" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>vocab <span class="op">=</span> counts.get_feature_names_out()</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> show_topics(a, vocab, n<span class="op">=</span><span class="dv">8</span>):</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Top-n vocabulary terms of a word-space vector a, largest weight first."""</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> [vocab[j] <span class="cf">for</span> j <span class="kw">in</span> np.argsort(a)[::<span class="op">-</span><span class="dv">1</span>][:n]]</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">10</span>):</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"v_</span><span class="sc">{</span>i<span class="sc">:2d}</span><span class="ss">: "</span> <span class="op">+</span> <span class="st">", "</span>.join(show_topics(Vh[i], vocab)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>v_ 0: ditto, critus, propagandist, surname, galacticentric, kindergarten, surreal, imaginative
v_ 1: jpeg, gif, file, color, quality, image, jfif, format
v_ 2: graphics, edu, pub, mail, 128, 3d, ray, ftp
v_ 3: jesus, god, matthew, people, atheists, atheism, does, graphics
v_ 4: image, data, processing, analysis, software, available, tools, display
v_ 5: god, atheists, atheism, religious, believe, religion, argument, true
v_ 6: space, nasa, lunar, mars, probe, moon, missions, probes
v_ 7: image, probe, surface, lunar, mars, probes, moon, orbit
v_ 8: argument, fallacy, conclusion, example, true, ad, argumentum, premises
v_ 9: space, larson, image, theory, universe, physical, nasa, material</code></pre>
</div>
</div>
<p>The first right singular vector is an outlier: it collects rare, document-specific words (<code>ditto</code>, <code>propagandist</code>, <code>galacticentric</code>) that separate individual documents most sharply; the top layer does idiosyncrasy work rather than topical work. From the second layer on the vectors are unmistakably topical: <span class="math inline">\mathbf{v}_1</span> and <span class="math inline">\mathbf{v}_2</span> are computer graphics (image formats in one, graphics newsgroup slang in the other); <span class="math inline">\mathbf{v}_3</span> and <span class="math inline">\mathbf{v}_5</span> are religion and atheism; <span class="math inline">\mathbf{v}_6</span> and <span class="math inline">\mathbf{v}_9</span> are space, one about missions and probes, one about cosmology; and <span class="math inline">\mathbf{v}_8</span> is the argumentation register (<code>fallacy</code>, <code>premises</code>, <code>ad argumentum</code>), typical of the two debate-heavy groups. The category structure of the corpus was never given to the algorithm; it emerges from the counts alone, which is the punchline of the unsupervised setting.</p>
<p>Two structural caveats temper the reading. First, the SVD’s topics are mutually <em>orthogonal</em> in word space, a constraint real topics do not satisfy, so overlapping subjects bleed into neighboring layers: <span class="math inline">\mathbf{v}_4</span> mixes image processing with generic tools, and <span class="math inline">\mathbf{v}_7</span> mixes space probes with image processing. Second, each layer is signed: the words at the bottom of a vector are the layer’s opposite pole, so a layer can pair a theme with the words it opposes. Both limitations motivate the nonnegative factorization of the next section.</p>
</section>
<section id="nonnegative-matrix-factorization" class="level2">
<h2 class="anchored" data-anchor-id="nonnegative-matrix-factorization">Nonnegative matrix factorization</h2>
<p>The SVD’s topics are signed: a document is a linear combination of layers in which positive and negative word weights can <em>cancel</em>. That is numerically optimal but semantically awkward: a topic that says “astronomy, minus religion” is a subtraction, not a theme. The <mark>nonnegative matrix factorization</mark> (NMF) removes the cancellation by forcing every factor to be nonnegative:</p>
<p><span class="math display">
\boxed{\ \mathbf{X} \approx \mathbf{W}\mathbf{H},
\qquad \mathbf{W}\in\mathbb{R}^{n\times k}_{\ge 0},\quad
\mathbf{H}\in\mathbb{R}^{k\times d}_{\ge 0},\ }
</span></p>
<p>fitting the model by minimizing <span class="math inline">\lVert \mathbf{X} - \mathbf{W}\mathbf{H}\rVert_F^2</span> over both factors. Each row of <span class="math inline">\mathbf{H}</span> is a topic–word weight vector, each row of <span class="math inline">\mathbf{W}</span> holds the <span class="math inline">k</span> topic weights of one document, and document <span class="math inline">i</span> is reconstructed as an <em>additive</em> combination of topic word lists:</p>
<p><span class="math display">
\mathbf{x}_i^{\mathsf T} \approx \sum_{r=1}^k w_{ir}\,\mathbf{h}_r .
</span></p>
<p>Nothing is subtracted: a document is a sum of topic contributions, each one a nonnegative scaling of a single topic’s word list. That is the interpretability argument for NMF: the factors read as parts, in the same spirit as the layer view of Chapter 3, but without signed weights that demand cancellation.</p>
<p>NMF is not exact and not unique: no closed form exists, the objective is nonconvex, and different initializations converge to different local minima. <code>sklearn</code>’s implementation alternates between updating <span class="math inline">\mathbf{W}</span> and <span class="math inline">\mathbf{H}</span> by multiplicative updates <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> and returns one of many valid factorizations.</p>
<div id="e3dd16a2" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-14T21:01:30.733859Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-14T21:01:30.733708Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-14T21:01:31.135536Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-14T21:01:31.134956Z&quot;}}" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn <span class="im">import</span> decomposition</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>k <span class="op">=</span> <span class="dv">5</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>clf <span class="op">=</span> decomposition.NMF(n_components<span class="op">=</span>k, random_state<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>W1 <span class="op">=</span> clf.fit_transform(X)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>H1 <span class="op">=</span> clf.components_</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(k):</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"topic </span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">: "</span> <span class="op">+</span> <span class="st">", "</span>.join(show_topics(H1[i], vocab)))</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"reconstruction error ||X - WH||_F: </span><span class="sc">{:.2f}</span><span class="st">"</span>.<span class="bu">format</span>(clf.reconstruction_err_))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>topic 0: jpeg, image, gif, file, color, images, format, quality
topic 1: edu, graphics, pub, mail, 128, ray, ftp, send
topic 2: space, launch, satellite, nasa, commercial, satellites, year, market
topic 3: jesus, god, people, matthew, atheists, does, atheism, said
topic 4: image, data, available, software, processing, ftp, edu, analysis
reconstruction error ||X - WH||_F: 683.40</code></pre>
</div>
</div>
<p>With <span class="math inline">k = 5</span> components the factorization finds the four categories: the two religion groups merge into a single topic (<code>jesus</code>, <code>god</code>, <code>atheists</code> covers both <code>alt.atheism</code> and <code>talk.religion.misc</code>), space gets one clean topic, and graphics splits across two near-duplicates: one about image formats (<code>jpeg</code>, <code>gif</code>, <code>color</code>), one about the graphics-technical register (<code>edu</code>, <code>pub</code>, <code>ray</code>, <code>ftp</code>), plus a fifth on image processing and software. The near-duplicate split is NMF’s non-uniqueness made visible: the objective has many local minima, and this run’s solver landed on one that separates graphics by register rather than merging it. Because <span class="math inline">\mathbf{W}</span> and <span class="math inline">\mathbf{H}</span> are nonnegative, each document is a pure <em>additive</em> mixture: the entry <span class="math inline">w_{ir}</span> is literally the amount of topic <span class="math inline">r</span> in document <span class="math inline">i</span>, with no negative weights to interpret away — the interpretability NMF trades for exactness and uniqueness.</p>
</section>
<section id="tfidf-weighting" class="level2">
<h2 class="anchored" data-anchor-id="tfidf-weighting">TF–IDF weighting</h2>
<p>Raw counts over-reward frequent words: a term like “don” or “people” appears in most documents and dominates the reconstruction even though it carries little topical information. <mark>Term frequency–inverse document frequency</mark> (TF–IDF) reweights each count by how <em>discriminative</em> the term is across the corpus. For term <span class="math inline">t</span> and document <span class="math inline">d</span>,</p>
<p><span class="math display">
\operatorname{tf}(t,d) = \frac{\text{count of } t \text{ in } d}{\text{total terms in } d},
\qquad
\operatorname{idf}(t) = \log\frac{n}{|\{d : t \in d\}|},
\qquad
\operatorname{tfidf}(t,d) = \operatorname{tf}(t,d)\cdot\operatorname{idf}(t),
</span></p>
<p>so a term is heavy only if it is frequent <em>within</em> a document and rare <em>across</em> the corpus. <a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> Any term appearing in nearly every document gets <span class="math inline">\operatorname{idf} \approx 0</span> and drops out of the reconstruction. <code>TfidfVectorizer</code> additionally L2-normalizes each document row, so document lengths stop dominating the fit.</p>
<div id="6947da71" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-14T21:01:31.137872Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-14T21:01:31.137718Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-14T21:01:31.542046Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-14T21:01:31.541311Z&quot;}}" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.feature_extraction.text <span class="im">import</span> TfidfVectorizer</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>tfidf <span class="op">=</span> TfidfVectorizer(stop_words<span class="op">=</span><span class="st">"english"</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>Xw <span class="op">=</span> tfidf.fit_transform(newsgroups.data)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>vocab_w <span class="op">=</span> tfidf.get_feature_names_out()</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>clf2 <span class="op">=</span> decomposition.NMF(n_components<span class="op">=</span>k, random_state<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>W2 <span class="op">=</span> clf2.fit_transform(Xw)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>H2 <span class="op">=</span> clf2.components_</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(k):</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"topic </span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">: "</span> <span class="op">+</span> <span class="st">", "</span>.join(show_topics(H2[i], vocab_w)))</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"reconstruction error ||Xw - WH||_F: </span><span class="sc">{:.3f}</span><span class="st">"</span>.<span class="bu">format</span>(clf2.reconstruction_err_))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>topic 0: people, don, think, just, like, objective, say, morality
topic 1: graphics, thanks, files, image, file, program, windows, know
topic 2: space, nasa, launch, shuttle, orbit, moon, lunar, earth
topic 3: ico, bobbe, tek, beauchaine, bronx, manhattan, sank, queens
topic 4: god, jesus, bible, believe, christian, atheism, does, belief
reconstruction error ||Xw - WH||_F: 43.713</code></pre>
</div>
</div>
<p>The reweighting sharpens the topical cores: the space topic now reads <code>space, nasa, launch, shuttle, orbit, moon, lunar, earth</code> and the religion topic <code>god, jesus, bible, believe, christian</code> — both cleaner than their count-based counterparts, several of whose slots went to generic English (<code>commercial</code>, <code>market</code>, <code>said</code>). The reweighting is not free, though: the debate register that the count model folded into the religion topic (<code>people</code>, <code>don</code>, <code>think</code>, <code>objective</code>, <code>morality</code>) now occupies its own component, and a new topic of rare proper nouns appears: <code>ico</code>, <code>bobbe</code>, <code>tek</code>, <code>beauchaine</code> (a prolific <code>alt.atheism</code> correspondent), <code>bronx</code>, <code>manhattan</code>, <code>sank</code>, <code>queens</code> — the lexical fingerprint of a few long threads. TF–IDF reorders which words dominate; it does not guarantee that every component is a theme.</p>
<p>The <code>reconstruction_err_</code> attribute reports <span class="math inline">\lVert \mathbf{X}_w - \mathbf{W}\mathbf{H}\rVert_F</span> after fitting, a monitor of fit quality on <em>the same matrix</em>: 43.7 on the weighted counts against 683 on the raw counts. The two numbers are not comparable: the matrices being reconstructed differ by the weighting, and a smaller error does not mean better topics, since the factorization is non-unique and extra components can always absorb noise instead of meaning.</p>
</section>
<section id="truncated-and-randomized-svd" class="level2">
<h2 class="anchored" data-anchor-id="truncated-and-randomized-svd">Truncated and randomized SVD</h2>
<p>The full SVD above densified the matrix and paid for every one of its <span class="math inline">2034</span> singular values even though only a handful were read. The exact algorithm costs <span class="math inline">\mathcal{O}(nd\cdot\min(n,d))</span> flops and needs the dense representation. For larger corpora (millions of documents, vocabularies in the hundreds of thousands) that is out of reach, but only <span class="math inline">k</span> layers are wanted. The <mark>randomized SVD</mark> computes the top <span class="math inline">k</span> singular layers directly in <span class="math inline">\mathcal{O}(ndk)</span> flops, working on the sparse matrix, in three steps:</p>
<ol type="1">
<li><strong>Sketch.</strong> Multiply <span class="math inline">\mathbf{X}</span> by a Gaussian matrix <span class="math inline">\mathbf{G}\in\mathbb{R}^{d\times(k+p)}</span>: the columns of <span class="math inline">\mathbf{Y}=\mathbf{X}\mathbf{G}</span> are random linear combinations of documents.</li>
<li><strong>Range finder.</strong> A QR factorization (Chapter 7) of <span class="math inline">\mathbf{Y}\in\mathbb{R}^{n\times(k+p)}</span> produces an orthonormal <span class="math inline">\mathbf{Q}</span> whose columns span the dominant <span class="math inline">k+p</span> left singular subspace of <span class="math inline">\mathbf{X}</span>.</li>
<li><strong>Small SVD.</strong> The matrix <span class="math inline">\mathbf{B}=\mathbf{Q}^{\mathsf T}\mathbf{X}</span> has only <span class="math inline">k+p</span> rows; its exact SVD <span class="math inline">\mathbf{B}=\widehat{\mathbf{U}}\boldsymbol{\Sigma}\mathbf{V}^{\mathsf T}</span> (Chapter 3) recovers the singular values and right singular vectors of <span class="math inline">\mathbf{X}</span>, since <span class="math inline">\mathbf{X}\approx\mathbf{Q}\mathbf{B}</span>.</li>
</ol>
<div id="93a839d9" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-14T21:01:31.543843Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-14T21:01:31.543683Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-14T21:01:31.633434Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-14T21:01:31.632271Z&quot;}}" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="annotated-cell-6"><pre class="sourceCode python code-annotation-code code-with-copy"><code class="sourceCode python"><span id="annotated-cell-6-1"><a href="#annotated-cell-6-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.utils.extmath <span class="im">import</span> randomized_svd</span>
<span id="annotated-cell-6-2"><a href="#annotated-cell-6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-6-3"><a href="#annotated-cell-6-3" aria-hidden="true" tabindex="-1"></a>t0 <span class="op">=</span> time.perf_counter()</span>
<span id="annotated-cell-6-4"><a href="#annotated-cell-6-4" aria-hidden="true" tabindex="-1"></a>Ur, sr, Vhr <span class="op">=</span> randomized_svd(X, n_components<span class="op">=</span>k, random_state<span class="op">=</span><span class="dv">1</span>)</span>
<span id="annotated-cell-6-5"><a href="#annotated-cell-6-5" aria-hidden="true" tabindex="-1"></a>t_rand <span class="op">=</span> time.perf_counter() <span class="op">-</span> t0</span>
<span id="annotated-cell-6-6"><a href="#annotated-cell-6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-6-7"><a href="#annotated-cell-6-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(k):</span>
<span id="annotated-cell-6-8"><a href="#annotated-cell-6-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"topic </span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">: "</span> <span class="op">+</span> <span class="st">", "</span>.join(show_topics(Vhr[i], vocab)))</span>
<span id="annotated-cell-6-9"><a href="#annotated-cell-6-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"randomized: </span><span class="sc">{</span>t_rand <span class="op">*</span> <span class="fl">1e3</span><span class="sc">:.0f}</span><span class="ss"> ms   full: </span><span class="sc">{</span>t_full<span class="sc">:.1f}</span><span class="ss"> s"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>topic 0: jpeg, image, edu, file, graphics, images, gif, data
topic 1: jpeg, gif, file, color, quality, image, jfif, format
topic 2: space, jesus, launch, god, people, satellite, matthew, atheists
topic 3: jesus, god, matthew, people, atheists, atheism, does, graphics
topic 4: image, data, processing, analysis, software, available, tools, display
randomized: 73 ms   full: 62.9 s</code></pre>
</div>
</div>
<p><strong>From scratch.</strong> The same three steps, hand-rolled as a function that returns the top-<span class="math inline">k</span> factors directly from the sparse matrix. The output compares its topics and singular values against the library call above.</p>
<div id="6a41d352" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-14T21:01:31.635578Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-14T21:01:31.635395Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-14T21:01:31.703056Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-14T21:01:31.701341Z&quot;}}" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> randomized_svd_scratch(A, k, n_oversamples<span class="op">=</span><span class="dv">10</span>, n_power<span class="op">=</span><span class="dv">3</span>, seed<span class="op">=</span><span class="dv">0</span>):</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    rng <span class="op">=</span> np.random.default_rng(seed)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    n, d <span class="op">=</span> A.shape</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    ell <span class="op">=</span> k <span class="op">+</span> n_oversamples</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    G <span class="op">=</span> rng.standard_normal((d, ell))</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    Y <span class="op">=</span> A <span class="op">@</span> G                                    <span class="co"># &lt;1&gt; sketch</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(n_power):</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>        Y <span class="op">=</span> A <span class="op">@</span> (A.T <span class="op">@</span> Y)                        <span class="co"># &lt;2&gt; power iterations</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    Q, _ <span class="op">=</span> np.linalg.qr(Y)                       <span class="co"># &lt;3&gt; range finder</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    B <span class="op">=</span> Q.T <span class="op">@</span> A                                  <span class="co"># &lt;4&gt; small matrix</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    Uhat, s, Vh <span class="op">=</span> np.linalg.svd(B, full_matrices<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> Q <span class="op">@</span> Uhat, s, Vh</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>Uz, sz, Vhz <span class="op">=</span> randomized_svd_scratch(X, k)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(k):</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"topic </span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">: "</span> <span class="op">+</span> <span class="st">", "</span>.join(show_topics(Vhz[i], vocab)))</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"singular values  sklearn:"</span>, np.<span class="bu">round</span>(sr, <span class="dv">4</span>))</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"singular values  scratch:"</span>, np.<span class="bu">round</span>(sz[:k], <span class="dv">4</span>))</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"|Vhr . Vhz^T| (topics up to sign):"</span>)</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(np.<span class="bu">round</span>(np.<span class="bu">abs</span>(Vhr <span class="op">@</span> Vhz[:k].T), <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>topic 0: jpeg, image, edu, file, graphics, images, gif, data
topic 1: jpeg, gif, file, color, quality, image, jfif, format
topic 2: space, jesus, launch, god, people, satellite, matthew, atheists
topic 3: space, launch, satellite, commercial, nasa, satellites, market, year
topic 4: image, data, processing, analysis, software, available, tools, display
singular values  sklearn: [433.927  291.5101 240.7114 220.0005 182.7448]
singular values  scratch: [433.927  291.5101 240.7094 220.0004 182.6595]
|Vhr . Vhz^T| (topics up to sign):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]</code></pre>
</div>
</div>
<p>The scratch implementation reproduces the library call: the first four singular values agree to better than <span class="math inline">10^{-5}</span> relative error, and the overlap matrix <span class="math inline">|\mathbf{V}_r\mathbf{V}_{rz}^{\mathsf T}|</span> is the identity up to roundoff: diagonal entries 1, off-diagonal entries below <span class="math inline">2.4\times10^{-4}</span>. Four of the five topic word lists agree exactly; the fifth, topic 3, is the sign-flipped twin of the library’s: its top words (<code>space</code>, <code>launch</code>, <code>satellite</code>, <code>commercial</code>) are exactly the words at the <em>bottom</em> of <code>sklearn</code>’s topic 3 (<code>jesus</code>, <code>god</code>, <code>matthew</code>). That is the sign ambiguity of Chapter 3 made concrete: singular vectors are determined only up to sign, and a flipped topic reads as its own anti-theme. Only the subspace spanned by the vectors is what the data determines, not the orientation of each basis vector. The fifth singular value lags by 0.05% (182.66 against 182.74): it sits in the nearly-degenerate pair <span class="math inline">\sigma_5/\sigma_6 \approx 1.09</span> at the edge of the retained range, where the power iterations converge most slowly, and the scratch run uses three of them where <code>sklearn</code>’s default uses seven.</p>
<p>Step # &lt;1&gt; samples the column space through <span class="math inline">k+p</span> random directions, the oversampling <span class="math inline">p</span> guarding against the slow spectrum of Figure <a href="#fig-svd-scree" class="quarto-xref">Figure&nbsp;1</a>. The power iterations # &lt;2&gt; multiply the sketch by <span class="math inline">\mathbf{X}\mathbf{X}^{\mathsf T}</span> at each pass, which squares the singular values: after <span class="math inline">q</span> iterations the sketch is dominated by directions with <span class="math inline">\sigma_i^{2q}</span>, exactly the amplification idea behind the power iteration of Chapter 9. The QR step # &lt;3&gt; turns the amplified sketch into an orthonormal basis <span class="math inline">\mathbf{Q}</span> of the dominant subspace (Chapter 7), and the exact SVD # &lt;4&gt; of the <span class="math inline">(k+p)\times d</span> matrix <span class="math inline">\mathbf{B}</span> costs <span class="math inline">\mathcal{O}(d(k+p)^2)</span> flops: the matrix is as wide as <span class="math inline">\mathbf{X}</span> but has only <span class="math inline">k+p</span> rows, so the factorization is cheap. The whole pipeline never densifies the data and never computes a singular value beyond the <span class="math inline">k</span> wanted: 126 milliseconds against 49 seconds for the exact SVD, and the gap only widens as the corpus grows.</p>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>This chapter put the low-rank machinery of Chapter 3 on its native ground: a <span class="math inline">2034\times 26576</span> term–document matrix of word counts. The SVD layers read as topics directly: the right singular vectors are word lists, and the first few recover the newsgroups’ actual subjects with no labels in sight. NMF replaces the signed layers with additive nonnegative parts, at the price of uniqueness; TF–IDF weighting sharpens the topics by downweighting corpus-wide words; and the randomized SVD computes the top layers in seconds on the sparse matrix via a Gaussian sketch, a QR range finder, and a small exact SVD: the QR of Chapter 7 and the layer view of Chapter 3, scaled to wide, sparse data.</p>
<p>Chapter 12 applies the same dominant-direction idea to the web: PageRank turns the link structure of the web into a matrix and finds the vector that best describes relative importance, an eigenvalue problem solved by power iteration, the Chapter 9 algorithm that resurfaces here as the range finder’s engine.</p>
</section>
<section id="problems" class="level2">
<h2 class="anchored" data-anchor-id="problems">Problems</h2>
<p>The problems exercise the machinery of this chapter: energy accounting of the SVD layers, the randomized-SVD sketch, TF–IDF weighting, and the behavior of power-law spectra. Notation follows the chapter: the term–document matrix is <span class="math inline">\mathbf{X}\in\mathbb{R}^{n\times d}</span> with SVD <span class="math inline">\mathbf{X} = \sum_i \sigma_i\,\mathbf{u}_i\mathbf{v}_i^{\mathsf T}</span>.</p>
<section id="p11.1-energy-captured-by-a-rank-k-truncation" class="level3">
<h3 class="anchored" data-anchor-id="p11.1-energy-captured-by-a-rank-k-truncation">[P11.1] Energy captured by a rank-<span class="math inline">k</span> truncation</h3>
<p>Let <span class="math inline">\mathbf{X}\in\mathbb{R}^{n\times d}</span> have SVD <span class="math inline">\mathbf{X} = \sum_{i=1}^{r} \sigma_i\,\mathbf{u}_i\mathbf{v}_i^{\mathsf T}</span> and let <span class="math inline">\mathbf{X}_k = \sum_{i=1}^{k} \sigma_i\,\mathbf{u}_i\mathbf{v}_i^{\mathsf T}</span> be its rank-<span class="math inline">k</span> truncation, the chapter’s <span class="math inline">k</span>-topic model.</p>
<ol type="a">
<li>Show that for orthonormal unit vectors <span class="math inline">\mathbf{u}, \mathbf{v}</span> and <span class="math inline">\sigma \ge 0</span>,</li>
</ol>
<p><span class="math display">\lVert \sigma\,\mathbf{u}\mathbf{v}^{\mathsf T}\rVert_F^2 = \sigma^2 .</span></p>
<ol start="2" type="a">
<li><p>The layers <span class="math inline">\mathbf{u}_i\mathbf{v}_i^{\mathsf T}</span> are orthogonal under the Frobenius inner product <span class="math inline">\langle \mathbf{M}, \mathbf{N}\rangle = \operatorname{tr}(\mathbf{M}^{\mathsf T}\mathbf{N})</span>. Show this, and use it to derive <span class="math inline">\lVert \mathbf{X}_k\rVert_F^2 = \sum_{i=1}^{k}\sigma_i^2</span> and <span class="math inline">\lVert \mathbf{X} - \mathbf{X}_k\rVert_F^2 = \sum_{i=k+1}^{r}\sigma_i^2</span>.</p></li>
<li><p>Conclude that the fraction of the Frobenius energy retained by the rank-<span class="math inline">k</span> truncation is</p></li>
</ol>
<p><span class="math display">\boxed{\;\frac{\lVert \mathbf{X}_k\rVert_F^2}{\lVert \mathbf{X}\rVert_F^2} = \frac{\sum_{i=1}^{k}\sigma_i^2}{\sum_{i=1}^{r}\sigma_i^2},\;}</span></p>
<p>and read the chapter’s newsgroups figure of 58% of the energy in the first ten layers as this ratio.</p>
</section>
<section id="p11.2-power-iteration-amplification-in-the-sketch" class="level3">
<h3 class="anchored" data-anchor-id="p11.2-power-iteration-amplification-in-the-sketch">[P11.2] Power iteration amplification in the sketch</h3>
<p>The randomized SVD of the chapter sketches the range of <span class="math inline">\mathbf{X}</span> by <span class="math inline">\mathbf{Y} = \mathbf{X}\mathbf{G}</span>, where <span class="math inline">\mathbf{G}\in\mathbb{R}^{d\times(k+p)}</span> is Gaussian, and <span class="math inline">q</span> power iterations replace the sketch by <span class="math inline">\mathbf{Y}_q = (\mathbf{X}\mathbf{X}^{\mathsf T})^q\,\mathbf{X}\mathbf{G}</span>. Let <span class="math inline">\mathbf{X} = \mathbf{U}\boldsymbol{\Sigma}\mathbf{V}^{\mathsf T}</span> be the reduced SVD.</p>
<ol type="a">
<li><p>Show that <span class="math inline">(\mathbf{X}\mathbf{X}^{\mathsf T})^q = \mathbf{U}\boldsymbol{\Sigma}^{2q}\mathbf{U}^{\mathsf T}</span>, and hence <span class="math inline">\mathbf{Y}_q = \mathbf{U}\boldsymbol{\Sigma}^{2q+1}\mathbf{V}^{\mathsf T}\mathbf{G}</span>.</p></li>
<li><p>Let <span class="math inline">\mathbf{g}_j</span> be the <span class="math inline">j</span>-th column of <span class="math inline">\mathbf{G}</span>. Show that the component of <span class="math inline">\mathbf{Y}_q\mathbf{e}_j</span> along the singular direction <span class="math inline">\mathbf{u}_i</span> has magnitude <span class="math inline">\sigma_i^{2q+1}\,|\mathbf{v}_i^{\mathsf T}\mathbf{g}_j|</span>, so the ratio of the <span class="math inline">i</span>-th to the <span class="math inline">\ell</span>-th direction’s content is <span class="math inline">(\sigma_i/\sigma_\ell)^{2q+1}</span> times a ratio of random factors.</p></li>
<li><p>For <span class="math inline">\sigma_1 &gt; \sigma_2</span> the dominant direction’s share of the sketch therefore grows like <span class="math inline">(\sigma_1/\sigma_2)^{2q}</span>, up to the random factors, which are <span class="math inline">\mathcal{O}(1)</span> with high probability. State the cost of one power iteration in terms of the nonzeros of <span class="math inline">\mathbf{X}</span>, and explain why the chapter’s scratch run needs them: the newsgroups spectrum decays as a power law, so the gap <span class="math inline">\sigma_1/\sigma_{k+1}</span> is small.</p></li>
</ol>
</section>
<section id="p11.3-tfidf-on-a-toy-corpus" class="level3">
<h3 class="anchored" data-anchor-id="p11.3-tfidf-on-a-toy-corpus">[P11.3] TF–IDF on a toy corpus</h3>
<p>Four documents over the two-term vocabulary <span class="math inline">\{\text{cat}, \text{dog}\}</span>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Document</th>
<th>Text</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td><code>cat cat cat</code></td>
</tr>
<tr class="even">
<td>1</td>
<td><code>cat dog</code></td>
</tr>
<tr class="odd">
<td>2</td>
<td><code>dog dog dog</code></td>
</tr>
<tr class="even">
<td>3</td>
<td><code>cat cat</code></td>
</tr>
</tbody>
</table>
<ol type="a">
<li>Compute the document frequency <span class="math inline">\operatorname{df}(t)</span>, the number of documents containing term <span class="math inline">t</span>, and the smoothed inverse document frequency of the chapter’s footnote convention,</li>
</ol>
<p><span class="math display">\operatorname{idf}(t) = \log\frac{n+1}{\operatorname{df}(t)+1} + 1, \qquad n = 4,</span></p>
<p>by hand. Verify the values against the <code>idf_</code> attribute of a fitted <code>TfidfVectorizer</code> with <code>np.allclose(..., atol=1e-6)</code>.</p>
<ol start="2" type="a">
<li><p>Verify that every row of the vectorized matrix has unit 2-norm, the L2 normalization the chapter attributes to <code>TfidfVectorizer</code>.</p></li>
<li><p>Report the entry <span class="math inline">(1, \text{cat})</span>, the weight of <code>cat</code> in document 1. Check it against the hand value <span class="math inline">\operatorname{idf}(\text{cat})/\sqrt{\operatorname{idf}(\text{cat})^2 + \operatorname{idf}(\text{dog})^2}</span>.</p></li>
</ol>
<p>The starter cell below builds the corpus and fits the vectorizer.</p>
<div id="2a610c6d" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-16T20:07:35.221038Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-16T20:07:35.220581Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-16T20:07:39.171892Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-16T20:07:39.170253Z&quot;}}" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.feature_extraction.text <span class="im">import</span> TfidfVectorizer</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>docs <span class="op">=</span> [<span class="st">"cat cat cat"</span>, <span class="st">"cat dog"</span>, <span class="st">"dog dog dog"</span>, <span class="st">"cat cat"</span>]</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>vec <span class="op">=</span> TfidfVectorizer()</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> vec.fit_transform(docs)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>vocab <span class="op">=</span> vec.get_feature_names_out()</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="bu">len</span>(docs)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="co"># (a) document frequencies and smoothed idf:</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="co"># df = np.asarray((X &gt; 0).sum(axis=0)).ravel()</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="co"># idf_calc = np.log((n + 1) / (df + 1)) + 1</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a><span class="co"># (b) row norms of the tfidf matrix:</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a><span class="co"># row_norms = np.linalg.norm(X.toarray(), axis=1)</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a><span class="co"># (c) the weight of 'cat' in document 1:</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a><span class="co"># w_cat_doc1 = X.toarray()[1, list(vocab).index('cat')]</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"vocabulary:"</span>, vocab.tolist())</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"idf (vectorizer):"</span>, np.<span class="bu">round</span>(vec.idf_, <span class="dv">6</span>))</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"row norms (vectorizer):"</span>, np.<span class="bu">round</span>(np.linalg.norm(X.toarray(), axis<span class="op">=</span><span class="dv">1</span>), <span class="dv">8</span>))</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"X[1, cat] ="</span>, <span class="bu">round</span>(X.toarray()[<span class="dv">1</span>, <span class="bu">list</span>(vocab).index(<span class="st">'cat'</span>)], <span class="dv">6</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>vocabulary: ['cat', 'dog']
idf (vectorizer): [1.223144 1.510826]
row norms (vectorizer): [1. 1. 1. 1.]
X[1, cat] = 0.629228</code></pre>
</div>
</div>
</section>
<section id="p11.4-energy-retention-in-practice" class="level3">
<h3 class="anchored" data-anchor-id="p11.4-energy-retention-in-practice">[P11.4] Energy retention in practice</h3>
<ol type="a">
<li><p>Implement <code>energy_retained(s, k)</code>, the ratio <span class="math inline">\sum_{i\le k} s_i^2 / \sum_i s_i^2</span> for a singular-value array <code>s</code>, the quantity of Problem 1(c).</p></li>
<li><p>Build a synthetic matrix with planted singular values <span class="math inline">\sigma_i = 1/i</span>, <span class="math inline">i = 1,\dots,40</span>: sample orthonormal <span class="math inline">\mathbf{U}\in\mathbb{R}^{50\times 40}</span> and <span class="math inline">\mathbf{V}\in\mathbb{R}^{40\times 40}</span> from QR decompositions of Gaussian matrices with seed 0, and set <span class="math inline">\mathbf{A} = \mathbf{U}\operatorname{diag}(\boldsymbol{\sigma})\mathbf{V}^{\mathsf T}</span>. Verify three properties of the function: <code>energy_retained(s, 40)</code> equals 1 up to roundoff; the fraction is monotone nondecreasing in <span class="math inline">k</span>; and it matches the direct Frobenius computation <span class="math inline">\lVert \mathbf{A}_k\rVert_F^2/\lVert \mathbf{A}\rVert_F^2</span> of the Eckart–Young truncation to <span class="math inline">10^{-10}</span>.</p></li>
<li><p>Report the fraction for <span class="math inline">k = 10</span>. The planted spectrum decays like the newsgroups spectrum of the chapter, whose ten-layer figure is 58%; compare the two numbers.</p></li>
</ol>
<p>The starter cell below sets up the matrix and its exact SVD.</p>
<div id="44a0a6fd" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-16T20:07:55.764404Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-16T20:07:55.764054Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-16T20:07:55.938924Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-16T20:07:55.937170Z&quot;}}" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> energy_retained(s, k):</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Fraction of the squared singular-value mass in the first k layers."""</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># return (s[:k] ** 2).sum() / (s ** 2).sum()</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">0</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>n, r <span class="op">=</span> <span class="dv">50</span>, <span class="dv">40</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>sigma <span class="op">=</span> <span class="fl">1.0</span> <span class="op">/</span> np.arange(<span class="dv">1</span>, r <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>U, _ <span class="op">=</span> np.linalg.qr(rng.standard_normal((n, r)))</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>V, _ <span class="op">=</span> np.linalg.qr(rng.standard_normal((r, r)))</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> U <span class="op">@</span> np.diag(sigma) <span class="op">@</span> V.T</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>U, s, Vh <span class="op">=</span> np.linalg.svd(A, full_matrices<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a><span class="co"># (b) checks, e.g. for k = 10:</span></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Ak = U[:, :k] @ np.diag(s[:k]) @ Vh[:k, :]</span></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a><span class="co"># direct = np.linalg.norm(Ak) ** 2 / np.linalg.norm(A) ** 2</span></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a><span class="co"># formula = energy_retained(s, k)</span></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"singular values s[:5]:"</span>, np.<span class="bu">round</span>(s[:<span class="dv">5</span>], <span class="dv">4</span>))</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"sum s^2:"</span>, <span class="bu">round</span>((s <span class="op">**</span> <span class="dv">2</span>).<span class="bu">sum</span>(), <span class="dv">6</span>))</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"energy_retained(s, r) should be 1.0; fill in (a) and (b)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>singular values s[:5]: [1.     0.5    0.3333 0.25   0.2   ]
sum s^2: 1.620244
energy_retained(s, r) should be 1.0; fill in (a) and (b)</code></pre>
</div>
</div>
</section>
<section id="p11.5-power-iterations-in-the-randomized-svd" class="level3">
<h3 class="anchored" data-anchor-id="p11.5-power-iterations-in-the-randomized-svd">[P11.5] Power iterations in the randomized SVD</h3>
<p><strong>Challenge.</strong> The chapter’s scratch randomized SVD ran three power iterations on the newsgroups matrix. This problem measures what they buy, on a synthetic matrix whose spectrum decays as a power law, like the real corpus of Figure <a href="#fig-svd-scree" class="quarto-xref">Figure&nbsp;1</a>.</p>
<ol type="a">
<li><p>Build <span class="math inline">\mathbf{A}\in\mathbb{R}^{200\times 150}</span> with planted singular values <span class="math inline">\sigma_i = i^{-1/2}</span>, <span class="math inline">i = 1,\dots,150</span>: orthonormal factors from QR decompositions of Gaussian matrices with seed 3, and <span class="math inline">\mathbf{A} = \mathbf{U}\operatorname{diag}(\boldsymbol{\sigma})\mathbf{V}^{\mathsf T}</span>.</p></li>
<li><p>For <span class="math inline">q \in \{0, 3, 10\}</span> power iterations, compute a randomized top-5 SVD with <span class="math inline">p = 5</span> oversampling and seed 11, and measure</p></li>
</ol>
<p><span class="math display">\mathrm{err}(q) = \max_{i \le 5}\, \frac{|\hat{\sigma}_i - \sigma_i|}{\sigma_i}, \qquad \mathrm{sub}(q) = \max_{i \le 5}\, \left(1 - |\hat{\mathbf{v}}_i^{\mathsf T}\mathbf{v}_i|\right),</span></p>
<p>the worst relative error of the recovered singular values and the worst alignment of the recovered topic vectors, up to the sign ambiguity of Chapter 3.</p>
<ol start="3" type="a">
<li><p>Verify numerically that <span class="math inline">\mathrm{err}(10) &lt; 10^{-6}</span> while <span class="math inline">\mathrm{err}(0) &gt; 10^{-2}</span>, and explain the ladder through Problem 2: with <span class="math inline">\sigma_1/\sigma_6 = \sqrt{6}</span>, the sketch’s content ratio for the sixth direction falls like <span class="math inline">(\sigma_6/\sigma_1)^{2q+1}</span>.</p></li>
<li><p>Probe <span class="math inline">q = 30</span>. The error rises again: the sketch’s component along direction 6 is proportional to <span class="math inline">\sigma_6^{2q+1}</span>, and <span class="math inline">(\sigma_6/\sigma_1)^{61} \approx 10^{-24}</span> sits below machine epsilon (<span class="math inline">2.2\times 10^{-16}</span>), so the tail directions are lost to roundoff and the sketch is numerically rank-one. Confirm that <span class="math inline">\mathrm{err}(30)</span> is large, and identify the threshold <span class="math inline">q</span> at which <span class="math inline">(\sigma_6/\sigma_1)^{2q+1}</span> crosses machine epsilon.</p></li>
</ol>
<p>The starter cell below provides the randomized SVD and the construction.</p>
<div id="ddb9b67a" class="cell" data-quarto-private-1="{&quot;key&quot;:&quot;execution&quot;,&quot;value&quot;:{&quot;iopub.execute_input&quot;:&quot;2026-08-16T20:08:24.426406Z&quot;,&quot;iopub.status.busy&quot;:&quot;2026-08-16T20:08:24.426189Z&quot;,&quot;iopub.status.idle&quot;:&quot;2026-08-16T20:08:24.587781Z&quot;,&quot;shell.execute_reply&quot;:&quot;2026-08-16T20:08:24.585875Z&quot;}}" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> rsvd(A, k, q, p<span class="op">=</span><span class="dv">5</span>, seed<span class="op">=</span><span class="dv">11</span>):</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Randomized top-k SVD of A with q power iterations, p oversampling."""</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    rng <span class="op">=</span> np.random.default_rng(seed)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    n, d <span class="op">=</span> A.shape</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    ell <span class="op">=</span> k <span class="op">+</span> p</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    G <span class="op">=</span> rng.standard_normal((d, ell))</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    Y <span class="op">=</span> A <span class="op">@</span> G</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(q):</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>        Y <span class="op">=</span> A <span class="op">@</span> (A.T <span class="op">@</span> Y)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    Q, _ <span class="op">=</span> np.linalg.qr(Y)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>    B <span class="op">=</span> Q.T <span class="op">@</span> A</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    _, s_hat, Vh_hat <span class="op">=</span> np.linalg.svd(B, full_matrices<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> s_hat, Vh_hat</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">3</span>)</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>n, d, k <span class="op">=</span> <span class="dv">200</span>, <span class="dv">150</span>, <span class="dv">5</span></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>sigma <span class="op">=</span> <span class="fl">1.0</span> <span class="op">/</span> np.sqrt(np.arange(<span class="dv">1</span>, d <span class="op">+</span> <span class="dv">1</span>))</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>U, _ <span class="op">=</span> np.linalg.qr(rng.standard_normal((n, d)))</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>V, _ <span class="op">=</span> np.linalg.qr(rng.standard_normal((d, d)))</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> U <span class="op">@</span> np.diag(sigma) <span class="op">@</span> V.T</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>Ue, s_exact, Vhe <span class="op">=</span> np.linalg.svd(A, full_matrices<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> q <span class="kw">in</span> (<span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">10</span>, <span class="dv">30</span>):</span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>    s_hat, Vh_hat <span class="op">=</span> rsvd(A, k, q)</span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>    <span class="co"># err = np.max(np.abs(s_hat[:k] - s_exact[:k]) / s_exact[:k])</span></span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>    <span class="co"># sub = np.max(1 - np.abs(np.diag(Vh_hat[:k] @ Vhe[:k].T)))</span></span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"q=</span><span class="sc">{</span>q<span class="sc">}</span><span class="ss">: s_hat = </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">round</span>(s_hat[:k], <span class="dv">4</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>q=0: s_hat = [0.8995 0.4669 0.4133 0.3293 0.314 ]
q=3: s_hat = [1.     0.7071 0.5773 0.4998 0.4466]
q=10: s_hat = [1.     0.7071 0.5774 0.5    0.4472]
q=30: s_hat = [1.     0.7071 0.5767 0.1839 0.1654]</code></pre>
</div>
</div>


</section>
</section>


<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a><div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>The multiplicative update rules of <a href="https://en.wikipedia.org/wiki/Non-negative_matrix_factorization">Lee and Seung</a>, which multiply the current factors by entrywise nonnegative correction ratios, so nonnegativity is preserved automatically.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p><code>sklearn</code> smooths the formula to <span class="math inline">\operatorname{idf}(t) = \log\big((n+1)/(\operatorname{df}_t+1)\big) + 1</span>; the convention changes the scale, not the ordering of terms.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ron-medina\.site");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../courses/cla/10-quadratic-forms.html" class="pagination-link" aria-label="10. Quadratic forms">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">10. Quadratic forms</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../courses/cla/12-pagerank.html" class="pagination-link" aria-label="12. PageRank">
        <span class="nav-page-text">12. PageRank</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>