bibliography: assets/references.bib

execute:
  freeze: true

project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - portfolio.qmd
    - notes/index.qmd
    - notes/*.qmd
    - essays/index.qmd
    - essays/*.qmd
    - learning/index.qmd
    - learning/*.qmd
    - photos.qmd
  preview:
    port: 4200
    browser: false

website:
  title: "Ron Medina &mdash; Resume"
  back-to-top-navigation: true
  page-navigation: true
  bread-crumbs: true
  reader-mode: true
  favicon: assets/favicon.jpg

  navbar:
    left:
      - href: portfolio.qmd
        text: portfolio
      - href: essays/index.qmd
        text: essays
      - href: learning/index.qmd
        text: learning
      - href: notes/index.qmd
        text: notes
      - href: photos.qmd
        text: photos

format:
  html:
    theme: united
    lightbox: true
    html-math-method: katex
    highlight-annotations: true
    toc: true
    toc-location: right
    css: assets/styles.css
