bibliography: assets/references.bib

execute:
  enabled: false

project:
  type: website
  output-dir: _site
  render:
    - index.ipynb
    - portfolio/portfolio.ipynb
    - notes/index.ipynb
    - notes/*.ipynb
    - essays/index.ipynb
    - essays/*.ipynb
    - learning/index.ipynb
    - learning/*.ipynb
    - photos/photos.ipynb
  preview:
    port: 4200
    browser: false

website:
  title: "Ron Medina &mdash; Resume"
  back-to-top-navigation: true
  page-navigation: true
  bread-crumbs: true
  reader-mode: true
  favicon: assets/favicon.jpg

  navbar:
    left:
      - href: portfolio/portfolio.ipynb
        text: portfolio
      - href: essays/index.ipynb
        text: essays
      - href: learning/index.ipynb
        text: learning
      - href: notes/index.ipynb
        text: notes
      - href: photos/photos.ipynb
        text: photos

format:
  html:
    theme: united
    lightbox: true
    html-math-method: katex
    highlight-annotations: true
    toc: true
    toc-location: right
    css: assets/styles.css
