function Pandoc(doc)
  if not quarto.doc.isFormat("html") then
    return nil
  end

  local fields = doc.meta.listing and doc.meta.listing.fields
  if not fields then
    return nil
  end

  local has_date = false
  for _, v in ipairs(fields) do
    if pandoc.utils.stringify(v) == "date" then
      has_date = true
      break
    end
  end
  if not has_date then
    return nil
  end

  local js = '<script>\n'
  js = js .. '(function() {\n'
  js = js .. '  var MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];\n'
  js = js .. '  var activeYear = null, activeMonth = null;\n'
  js = js .. '  var origSetHash = null;\n'
  js = js .. '\n'
  js = js .. '  function initDateFilter() {\n'
  js = js .. '    var list = window["quarto-listings"] && window["quarto-listings"]["listing-listing"];\n'
  js = js .. '    if (!list) return;\n'
  js = js .. '    var sidebar = document.getElementById("quarto-margin-sidebar");\n'
  js = js .. '    if (!sidebar) return;\n'
  js = js .. '\n'
  js = js .. '    var yearMap = {};\n'
  js = js .. '    list.items.forEach(function(item) {\n'
  js = js .. '      var ms = parseInt(item.elm.getAttribute("data-listing-date-sort"));\n'
  js = js .. '      if (isNaN(ms)) return;\n'
  js = js .. '      var d = new Date(ms);\n'
  js = js .. '      var y = d.getFullYear();\n'
  js = js .. '      var m = d.getMonth();\n'
  js = js .. '      if (!yearMap[y]) yearMap[y] = {};\n'
  js = js .. '      if (!yearMap[y][m]) yearMap[y][m] = 0;\n'
  js = js .. '      yearMap[y][m]++;\n'
  js = js .. '    });\n'
  js = js .. '\n'
  js = js .. '    var yearNums = Object.keys(yearMap).map(Number).sort(function(a,b){return b-a;});\n'
  js = js .. '    if (!yearNums.length) return;\n'
  js = js .. '\n'
  js = js .. '    var container = document.createElement("div");\n'
  js = js .. '    container.className = "df-container";\n'
  js = js .. '\n'
  js = js .. '    var hdr = document.createElement("h5");\n'
  js = js .. '    hdr.className = "df-title";\n'
  js = js .. '    hdr.textContent = "Dates";\n'
  js = js .. '    container.appendChild(hdr);\n'
  js = js .. '\n'
  js = js .. '    yearNums.forEach(function(year) {\n'
  js = js .. '      var monthNums = Object.keys(yearMap[year]).map(Number).sort(function(a,b){return a-b;});\n'
  js = js .. '      var yearTotal = 0;\n'
  js = js .. '      monthNums.forEach(function(m){ yearTotal += yearMap[year][m]; });\n'
  js = js .. '\n'
  js = js .. '      var sec = document.createElement("div");\n'
  js = js .. '      sec.className = "df-year-section";\n'
  js = js .. '      sec.setAttribute("data-year", year);\n'
  js = js .. '\n'
  js = js .. '      var yp = document.createElement("div");\n'
  js = js .. '      yp.className = "df-year-pill category";\n'
  js = js .. '      yp.innerHTML = \'<span class="df-chevron">&#9656;</span> \' + year + \' <span class="quarto-category-count">(\' + yearTotal + \')</span>\';\n'
  js = js .. '\n'
  js = js .. '      var mc = document.createElement("div");\n'
  js = js .. '      mc.className = "df-months";\n'
  js = js .. '\n'
  js = js .. '      var allM = document.createElement("div");\n'
  js = js .. '      allM.className = "df-month-pill category";\n'
  js = js .. '      allM.setAttribute("data-month", "all");\n'
  js = js .. '      allM.innerHTML = \'All <span class="quarto-category-count">(\' + yearTotal + \')</span>\';\n'
  js = js .. '      mc.appendChild(allM);\n'
  js = js .. '\n'
  js = js .. '      monthNums.forEach(function(m) {\n'
  js = js .. '        var mp = document.createElement("div");\n'
  js = js .. '        mp.className = "df-month-pill category";\n'
  js = js .. '        mp.setAttribute("data-month", m);\n'
  js = js .. '        mp.innerHTML = MONTHS[m] + \' <span class="quarto-category-count">(\' + yearMap[year][m] + \')</span>\';\n'
  js = js .. '        mc.appendChild(mp);\n'
  js = js .. '      });\n'
  js = js .. '\n'
  js = js .. '      yp.addEventListener("click", function() {\n'
  js = js .. '        var wasExpanded = sec.classList.contains("df-expanded");\n'
  js = js .. '        document.querySelectorAll(".df-year-section").forEach(function(s) {\n'
  js = js .. '          s.classList.remove("df-expanded");\n'
  js = js .. '        });\n'
  js = js .. '        document.querySelectorAll(".df-month-pill").forEach(function(p) {\n'
  js = js .. '          p.classList.remove("df-active");\n'
  js = js .. '        });\n'
  js = js .. '        if (wasExpanded) {\n'
  js = js .. '          activeYear = null;\n'
  js = js .. '          activeMonth = null;\n'
  js = js .. '        } else {\n'
  js = js .. '          sec.classList.add("df-expanded");\n'
  js = js .. '          activeYear = year;\n'
  js = js .. '          activeMonth = "all";\n'
  js = js .. '          allM.classList.add("df-active");\n'
  js = js .. '        }\n'
  js = js .. '        updateHash();\n'
  js = js .. '        applyAllFilters();\n'
  js = js .. '      });\n'
  js = js .. '\n'
  js = js .. '      allM.addEventListener("click", function() {\n'
  js = js .. '        document.querySelectorAll(".df-month-pill").forEach(function(p) {\n'
  js = js .. '          p.classList.remove("df-active");\n'
  js = js .. '        });\n'
  js = js .. '        allM.classList.add("df-active");\n'
  js = js .. '        activeYear = year;\n'
  js = js .. '        activeMonth = "all";\n'
  js = js .. '        updateHash();\n'
  js = js .. '        applyAllFilters();\n'
  js = js .. '      });\n'
  js = js .. '\n'
  js = js .. '      monthNums.forEach(function(m) {\n'
  js = js .. '        var pills = mc.querySelectorAll(".df-month-pill[data-month]\");\n'
  js = js .. '        for (var i = 0; i < pills.length; i++) {\n'
  js = js .. '          if (parseInt(pills[i].getAttribute("data-month")) === m) {\n'
  js = js .. '            (function(pill, monthVal) {\n'
  js = js .. '              pill.addEventListener("click", function() {\n'
  js = js .. '                document.querySelectorAll(".df-month-pill").forEach(function(p) {\n'
  js = js .. '                  p.classList.remove("df-active");\n'
  js = js .. '                });\n'
  js = js .. '                pill.classList.add("df-active");\n'
  js = js .. '                activeYear = year;\n'
  js = js .. '                activeMonth = monthVal;\n'
  js = js .. '                updateHash();\n'
  js = js .. '                applyAllFilters();\n'
  js = js .. '              });\n'
  js = js .. '            })(pills[i], m);\n'
  js = js .. '            break;\n'
  js = js .. '          }\n'
  js = js .. '        }\n'
  js = js .. '      });\n'
  js = js .. '\n'
  js = js .. '      sec.appendChild(yp);\n'
  js = js .. '      sec.appendChild(mc);\n'
  js = js .. '      container.appendChild(sec);\n'
  js = js .. '    });\n'
  js = js .. '\n'
  js = js .. '    sidebar.appendChild(container);\n'
  js = js .. '    overrideFilterFns();\n'
  js = js .. '    restoreFromHash();\n'
  js = js .. '  }\n'
  js = js .. '\n'
  js = js .. '  function applyAllFilters() {\n'
  js = js .. '    var cat = getActiveCategory();\n'
  js = js .. '    var listingIds = Object.keys(window["quarto-listings"]);\n'
  js = js .. '    for (var i = 0; i < listingIds.length; i++) {\n'
  js = js .. '      var list = window["quarto-listings"][listingIds[i]];\n'
  js = js .. '      if (!list) continue;\n'
  js = js .. '      if (!cat && activeYear === null) {\n'
  js = js .. '        list.filter();\n'
  js = js .. '        continue;\n'
  js = js .. '      }\n'
  js = js .. '      list.filter(function(item) {\n'
  js = js .. '        if (cat) {\n'
  js = js .. '          var cats = decodeURIComponent(atob(item.values().categories)).split(",");\n'
  js = js .. '          if (!cats.includes(cat)) return false;\n'
  js = js .. '        }\n'
  js = js .. '        if (activeYear !== null) {\n'
  js = js .. '          var ms = parseInt(item.elm.getAttribute("data-listing-date-sort"));\n'
  js = js .. '          if (isNaN(ms)) return false;\n'
  js = js .. '          var d = new Date(ms);\n'
  js = js .. '          if (d.getFullYear() !== activeYear) return false;\n'
  js = js .. '          if (activeMonth !== null && activeMonth !== "all" && d.getMonth() !== activeMonth) return false;\n'
  js = js .. '        }\n'
  js = js .. '        return true;\n'
  js = js .. '      });\n'
  js = js .. '    }\n'
  js = js .. '  }\n'
  js = js .. '\n'
  js = js .. '  function getActiveCategory() {\n'
  js = js .. '    var el = document.querySelector(".quarto-listing-category .category.active");\n'
  js = js .. '    if (!el) return null;\n'
  js = js .. '    var v = el.getAttribute("data-category");\n'
  js = js .. '    if (!v || v === "") return null;\n'
  js = js .. '    return decodeURIComponent(atob(v));\n'
  js = js .. '  }\n'
  js = js .. '\n'
  js = js .. '  function overrideFilterFns() {\n'
  js = js .. '    origSetHash = window.setHash;\n'
  js = js .. '    window.setHash = function(obj) {\n'
  js = js .. '      var h = (typeof window.getHash === "function") ? (window.getHash() || {}) : {};\n'
  js = js .. '      for (var k in obj) { h[k] = obj[k]; }\n'
  js = js .. '      origSetHash(h);\n'
  js = js .. '    };\n'
  js = js .. '    window.filterListingCategory = function() {\n'
  js = js .. '      applyAllFilters();\n'
  js = js .. '    };\n'
  js = js .. '  }\n'
  js = js .. '\n'
  js = js .. '  function updateHash() {\n'
  js = js .. '    var h = (typeof window.getHash === "function") ? (window.getHash() || {}) : {};\n'
  js = js .. '    if (activeYear !== null) { h.year = activeYear; } else { delete h.year; }\n'
  js = js .. '    if (activeMonth !== null && activeMonth !== "all") { h.month = activeMonth; } else { delete h.month; }\n'
  js = js .. '    var hash = Object.keys(h).map(function(k){return k+"="+h[k];}).join("&");\n'
  js = js .. '    window.history.pushState(null, null, hash ? "#"+hash : window.location.pathname);\n'
  js = js .. '  }\n'
  js = js .. '\n'
  js = js .. '  function restoreFromHash() {\n'
  js = js .. '    var h = (typeof window.getHash === "function") ? window.getHash() : null;\n'
  js = js .. '    if (!h || !h.year) return;\n'
  js = js .. '    activeYear = parseInt(h.year);\n'
  js = js .. '    activeMonth = h.month !== undefined ? parseInt(h.month) : "all";\n'
  js = js .. '    var sec = document.querySelector(".df-year-section[data-year=\\"" + activeYear + "\\"]");\n'
  js = js .. '    if (sec) {\n'
  js = js .. '      sec.classList.add("df-expanded");\n'
  js = js .. '      if (activeMonth !== "all") {\n'
  js = js .. '        var pill = sec.querySelector(".df-month-pill[data-month=\\"" + activeMonth + "\\"]");\n'
  js = js .. '        if (pill) pill.classList.add("df-active");\n'
  js = js .. '      } else {\n'
  js = js .. '        var allPill = sec.querySelector(".df-month-pill[data-month=\\"all\\"]");\n'
  js = js .. '        if (allPill) allPill.classList.add("df-active");\n'
  js = js .. '      }\n'
  js = js .. '    }\n'
  js = js .. '    applyAllFilters();\n'
  js = js .. '  }\n'
  js = js .. '\n'
  js = js .. '  function boot() {\n'
  js = js .. '    if (window["quarto-listings"] && window["quarto-listings"]["listing-listing"]) {\n'
  js = js .. '      initDateFilter();\n'
  js = js .. '    } else {\n'
  js = js .. '      setTimeout(boot, 50);\n'
  js = js .. '    }\n'
  js = js .. '  }\n'
  js = js .. '\n'
  js = js .. '  if (document.readyState === "loading") {\n'
  js = js .. '    document.addEventListener("DOMContentLoaded", function() { boot(); });\n'
  js = js .. '  } else {\n'
  js = js .. '    boot();\n'
  js = js .. '  }\n'
  js = js .. '})();\n'
  js = js .. '</script>\n'

  table.insert(doc.blocks, pandoc.RawBlock("html", js))
  return doc
end
